name: 'echo_analytics'
version: '1.0.0'
config-version: 2

profile: 'echo'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  echo_analytics:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: ephemeral
    dimensions:
      +materialized: table
      +schema: dimensions
      +tags: ['dimensions', 'scd2']
    facts:
      +materialized: incremental
      +schema: facts
      +tags: ['facts']
    marts:
      +materialized: table
      finance:
        +schema: finance
      marketing:
        +schema: marketing
      experiments:
        +schema: experiments

vars:
  start_date: '2024-01-01'
  currency: 'USD'
